### ISSUE TITLE
[BUG]: `requests` not getting installed as part of requirements.txt

### ISSUE THREAD

**Issue by Benjin** [wasi-master/13ft#11]
### Description of the bug

I had to add `RUN pip install requests` to the dockerfile in order to get it to run.

### Steps To Reproduce

1. Clone
2. Run `docker-compose up`

Error:
![image](https://github.com/wasi-master/13ft/assets/1609827/e9b5cc04-7495-4ac2-ad58-7d52eec2c311)

### Additional Information

Linux-style containers running on a Windows 10 host

**Comment by wasi-master** [comment]
Thanks for the report, looking into it

**Comment by wasi-master** [comment]
Found the problem, working on a fix

**Comment by wasi-master** [comment]
Published to [DockerHub](https://hub.docker.com/layers/wasimaster/13ft/0.2.3/images/sha256-0a0c57b8aaf6800a4ca95b6360b5910bc609ce605cb3a7fef0e553fc9d2d470f?context=repo) and [ghcr.io](https://github.com/wasi-master/13ft/pkgs/container/13ft/143368643?tag=0.2.3)
