### ISSUE TITLE
A 'latest' tag

### ISSUE THREAD

**Issue by imTHAI** [wasi-master/13ft#12]
### Description

Hello,
Can you make available a 'latest' tag for the docker version ? I'd like to incorporate your docker into a template but right now I have to set the version as a tag. 
The problem is when people download/use the template, as the tag is written in the template, it won't be updated the day you will publish a new one. With a 'latest' tag always corresponding to the last stable version available, it would solve this problem.

Thks

**Comment by wasi-master** [comment]
Yeah I'll do this a bit later

**Comment by wasi-master** [comment]
Done
