### ISSUE TITLE
[FEAT]: ARM support

### ISSUE THREAD

**Issue by jbonadiman** [wasi-master/13ft#13]
### Description

Raising this to ask for ARM support in the images in docker hub. I don't know exactly how you are uploading the image artifacts to docker hub, but I do know that using github actions is a matter of using the matrix strategy to build to different archs

**Comment by wasi-master** [comment]
I am a bit busy at the moment and don't really have the time to implement this. Any help is appreciated to make the process easier somehow.

**Comment by jbonadiman** [comment]
> I am a bit busy at the moment and don't really have the time to implement this. Any help is appreciated to make the process easier somehow.

Since you said you were a bit busy, I took the liberty to create a PR implementing a CI/CD pipeline with multi-arch: #15.
I already tested against my account/instance and it seems to be working fine.
Hope you like it, and I'm open to suggestions on how to improve it.

**Comment by wasi-master** [comment]
@jbonadiman Thank you very much ❤️. Your help is greatly appreciated.
