### ISSUE TITLE
[FEAT]: A build for arm64

### ISSUE THREAD

**Issue by upamanyudas** [wasi-master/13ft#16]
### Description

trying to run this in portainer on a raspberry pi, would love a arm64 build. ty

**Comment by wasi-master** [comment]
Available on arm via [dockerhub](https://hub.docker.com/layers/wasimaster/13ft/latest/images/sha256-d0440c947a5d500dbfd9d144b588a5a76591018f68316a7ebac02d162533a212?context=explore) now
