### ISSUE TITLE
[FEAT]: please publish a release

### ISSUE THREAD

**Issue by lapineige** [wasi-master/13ft#2]
### Description

I would like to package this software as a [Yunohost](yunohost.org/) app.
For this, I need a released version, so that I can use its URL to download the app.

Could you please make a release version for your software ?

Thank you

**Comment by wasi-master** [comment]
Okay, what do you need the release to have?

**Comment by lapineige** [comment]
Only what's needed to run the app.

Additional question : is there any other dependencies than flask ?
If that's the case, a `requirements.txt` file to list dependencies would be great (https://forum.yunohost.org/t/help-for-new-app-packaging-13ft-12ft-io-alternative-bypass-paywalls/22665/4) but that's not mandatory for us to package it.

WIP here : https://github.com/YunoHost-Apps/13ft_ynh

**Comment by wasi-master** [comment]
@lapineige Released v0.1.0 at https://github.com/wasi-master/13ft/releases/tag/v0.1.0 

It has the source code in zip format as usual but I've also added the index.html and index.py files separately if you need them

**Comment by lapineige** [comment]
Actually I believe I only need index.html and index.py in a single file.
I don't know if having more files is a problem or not, but it's a bit of a pity to download 10MB of data for a 2.5KB script :smile:

I don't think Yunohost can handle simply multiple file links.

**Comment by wasi-master** [comment]
@lapineige okay I'll see what I can do

**Comment by wasi-master** [comment]
@lapineige I've added a portable.py file that has the index.html and index.py in a single file

**Comment by lapineige** [comment]
That's perfect, thanks a lot !

I'll let you know how it's going :)

**Comment by lapineige** [comment]
Perfect !
