### ISSUE TITLE
[FEAT]: Docker Compose Based Setup

### ISSUE THREAD

**Issue by accforgithubtest** [wasi-master/13ft#7]
### Description

This is a neat project and in the interest of expanding this being useful to more people, I want to propose the idea of dockerizing this application. An Ideal solution would be

1. Containerize this application.
2. Publicly available images on dockerhib / ghcr / etc (multiple container registries please)
3. Readme updated with instructions on how to selfhost using docker-compose.

Thanks again for this awesome project, ope to see this containerized !

**Comment by wasi-master** [comment]
Good Idea! I have thought about doing this but the problem is that I don’t have sufficirnt docker experience :(

**Comment by recklessop** [comment]
i have this working, will create a pull request shortly

**Comment by wasi-master** [comment]
> i have this working, will create a pull request shortly

Thank you very much

**Comment by wasi-master** [comment]
Published to dockerhub: https://hub.docker.com/r/wasimaster/13ft

**Comment by wasi-master** [comment]
Published to GitHub Container Registry: https://github.com/wasi-master/13ft/pkgs/container/13ft

**Comment by a10kiloham** [comment]
this is what's now died i think
